# Generated by Django 3.0.7 on 2020-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('deposito', 'Depósito'), ('pagueseguro', 'PagueSeguro'), ('paypal', 'PayPal')], default='deposito', max_length=20, verbose_name='Opção de Pagamento'),
        ),
    ]
